config/routes.rb
Rails.application.routes.draw do
  root "videos#index"

  devise_for :users, controllers: { registrations: 'users'}

  resources :videos, only: [:index, :show] do
    resources :comments
  end

  resources :sessions, only: [:show, :create, :destroy]

  resources :users, only: [:create, :show] do
    resources :videos, only: [:new, :create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :decks
  has_many :games, :through => :decks

  validates :catagory, presence: true
  validates :body, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :game

  validates :user_id, presence: true
  validates :game_id, presence: true
  validates :body, presence: true
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :card
  belongs_to :game

  validates :card_id, presence: true
  validates :game_id, presence: true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :decks
  has_many :cards, :through => :decks

  mount_uploader :vid, VideoRecordingUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :games
  has_many :comments

  validates :username, presence: true

  mount_uploader :avatar, AvatarUploader
  acts_as_token_authenticatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
  mount_uploader :vid, VideoRecordingUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  acts_as_token_authentication_handler_for User, fallback: :none
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(comment_params)
    show_comment = { id: comment.id, body: comment.body, user: comment.user }

    respond_to do |format|
      if comment.save
        format.json { render json: show_comment, status: :created }
      else
        format.json { head(:unauthorized) }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :game_id, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def show
    respond_to do |format|
      format.json { current_user ? head(:ok) : head(:unauthorized) }
    end
  end

  def create
    user = User.where(email: params[:email]).first

    respond_to do |format|
      if user.valid_password?(params[:password])
        format.json { render json: user.as_json(only: [:id, :email, :authentication_token, :admin]), status: :created }
      else
        format.json { head(:unauthorized) }
      end
    end
  end

  def destroy
    current_user.authentication_token = nil
    respond_to do |format|
      format.json { current_user.save ? head(:ok) : head(:unauthorized) }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if User.find(params[:id]).admin
      @games = Game.all
      @display = []

      @games.each do |game|
        @display << {id: game.id, video: game.vid, user: game.user.username, recordedDate: game.created_at.strftime("%m/%d/%Y"), cards: game.cards}
      end
    else
      @games = Game.where(user: params[:id])
      @display = []

      @games.each do |game|
        @display << {id: game.id, video: game.vid, recordedDate: game.created_at.strftime("%m/%d/%Y"), cards: game.cards}
      end
    end
  end

  def create
    user = User.new(user_params)

    respond_to do |format|
      if user.save
        format.json { render json: user.as_json(only: [:id, :email, :authentication_token, :admin]), status: :created }
      else
        format.json { head(:unauthorized) }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :avatar, :admin, :username, :industry)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def index
    @display = []
    @games = Game.all
    @games.each do |game|
      @display << {id: game.id, user: game.user.username, industry: game.user.industry, video: game.vid, recordedDate: game.created_at.strftime("%m/%d/%Y"), cards: game.cards}
    end

    respond_to do |format|
      format.html { render :index }
    end
  end

  def show
    @game = Game.find(params[:id])
    @date = @game.created_at.strftime("%m/%d/%Y")
    @user = @game.user
    @deck = @game.cards
    comments = @game.comments
    @game_comments = comments.map {|comment| { id: comment.id, body: comment.body, user: comment.user }}

    respond_to do |format|
      format.html { render :show }
    end
  end

  def new
    @game = Game.create(user: User.find(params[:user_id]))
    Deck.create(game: @game, card: (Card.where(catagory: "Opener")[rand(0..3)]))
    Deck.create(game: @game, card: (Card.where(catagory: "Question")[rand(0..3)]))
    Deck.create(game: @game, card: (Card.where(catagory: "Personal")[rand(0..3)]))
    Deck.create(game: @game, card: (Card.where(catagory: "Closer")[rand(0..3)]))

    @deck = @game.cards

    respond_to do |format|
      format.html { render :new }
    end
  end

  def create
    vid = request.body
    @game = Game.where(user: User.find(params[:user_id])).last
    @game.vid = vid

    respond_to do |format|
      if @game.save!
        format.json { render json: @game }
      else
        format.json { render json: @game.errors.full_messages.join(' , ') }
      end
    end
  end

  def destroy
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.destroy
        format.json { head(:ok) }
      else
        format.json { head(:unauthorized) }
      end
    end
  end

  def all
    @games = Game.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/videos/index.html.erb
  <h1>Admin Panel</h1>

  <ul>
    <% @games.each do |game| %>
      <li>
        <%= game.user.username %>'s game
        <ul>
          <li>
            Recorded on: <%= game.created_at.strftime("%m/%d/%Y") %>
          </li>
          <li>
            <video controls>
              <source src="<%= game.vid.url %>" type="video/mp4"/>
            </video>
          </li>
          <li>
            <%= button_to "Delete", user_video_path(game.user.id, game.id), data: { confirm: "Are you sure?" }, method: :delete %>
          </li>
        </ul>
      </li>
    <% end %>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Interview Game</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_pack_tag 'video-test-bundle' %>
  </head>

  <body>
    <%= react_component("App", prerender: false) %>

    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1 class="text-center">My Games</h1>

<%= react_component("AppGamesPage", props: { games: @display }, prerender: false) %>

app/views/videos/index.html.erb
<h1 class="text-center">Recorded Games</h1>

<%= react_component("AppIndexPage", props: {games: @display}, prerender: false) %>

app/views/videos/new.html.erb
<%= react_component("AppGamePage", props: { deck: @deck }, prerender: false) %>

app/views/videos/show.html.erb
<%= react_component("AppShowPage", props: { game: @game, date: @date, user: @user, deck: @deck, comments: @game_comments}, prerender: false) %>